version: '3.8'
services:
  odoo:
    image: odoo:18
    depends_on:
      - db
    build:
      context: ./18_file
      dockerfile: Dockerfile_ver2
    ports:
      - "5050:8069"
      - "5051:8072"
    restart: unless-stopped
    volumes:
      - ./odoo-web-data:/var/lib/odoo
      - ./config/odoo.conf:/etc/odoo/odoo.conf
      - ./custom-addons:/mnt/extra-addons
#      - ./enterprise:/opt/enterprise
      - ./log:/opt/log
    environment:
      - HOST=db
      - DB_USER=odoo
      - DB_PASSWORD=odoo
    networks:
      - odoo
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8069/web/database/manager || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 60s
  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      # - POSTGRES_DB=odoo
    networks:
      - odoo

networks:
  odoo:
    external: true
    driver: bridge